x-redis: &x-redis
  image: rediswarm/rediswarm:${REDISWARM_VERSION:-main}
  networks:
    - rediswarm
  secrets:
    - REDISWARM_SECRET

x-deploy: &x-deploy-default
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  update_config:
    parallelism: 1
    delay: 10s
    failure_action: rollback
    monitor: 120s
    max_failure_ratio: 0.3
  rollback_config:
    parallelism: 1
    delay: 10s
    failure_action: pause
    monitor: 120s
    max_failure_ratio: 0.3

networks:
  rediswarm:

volumes:
  redis:
  redis-config:
  sentinel-config:

secrets:
  REDISWARM_SECRET:
    file: secrets/REDISWARM_SECRET

configs:
  haproxy.cfg:
    template_driver: golang
    file: configs/haproxy.cfg

services:
  redis:
    image: haproxytech/haproxy-alpine:latest
    secrets:
      - REDISWARM_SECRET
    networks:
      - rediswarm
    ports:
      - "8404:8404"
      - "6379:6379"
      - "6380:6380"
    configs:
      - source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    deploy: 
      <<: *x-deploy-default
      replicas: 1

  sentinel:
    <<: *x-redis
    hostname: sentinel-{{.Task.Slot}}
    environment:
      - REDISWARM_MODE=sentinel
      - REDISWARM_SLOT={{.Task.Slot}}
      - REDISWARM_SECRET_FILE=/run/secrets/REDISWARM_SECRET
      - REDIS_HOSTNAME_PREFIX=${REDIS_HOSTNAME_PREFIX:-replica-}
      - REDIS_SENTINEL_HOSTNAME_PREFIX=${REDIS_SENTINEL_HOSTNAME_PREFIX:-sentinel-}
    volumes:
      - sentinel-config:/etc/redis/config
    deploy:
      <<: *x-deploy-default
      replicas: ${REDIS_SENTINEL_REPLICAS:-3}
      placement:
        constraints:
          - node.labels.redis-sentinel == true

  replica:
    <<: *x-redis
    hostname: replica-{{.Task.Slot}}
    environment:
      - REDISWARM_MODE=redis
      - REDISWARM_SLOT={{.Task.Slot}}
      - REDISWARM_SECRET_FILE=/run/secrets/REDISWARM_SECRET
      - REDIS_HOSTNAME_PREFIX=${REDIS_HOSTNAME_PREFIX:-replica-}
      - REDIS_SENTINEL_ADDR=${REDIS_SENTINEL_ADDR:-sentinel}
    volumes:
      - redis:/data
      - redis-config:/etc/redis/config
    depends_on:
      - sentinel
    deploy:
      <<: *x-deploy-default
      replicas: ${REDIS_REPLICAS:-5}
      placement:
        constraints:
          - node.labels.redis == true
