networks:
  rediswarm:

volumes:
  redis:
    name: redis-{{.Task.Slot}}
  redis-config:
    name: redis-config-{{.Task.Slot}}
  sentinel-config:
    name: sentinel-config-{{.Task.Slot}}

secrets:
  REDIS_SWARM_SECRET:
    file: secrets/REDIS_SWARM_SECRET

configs:
  redis.conf.template:
    template_driver: golang
    file: configs/redis.conf.template
  sentinel.conf.template:
    template_driver: golang
    file: configs/sentinel.conf.template
  haproxy.cfg:
    template_driver: golang
    file: configs/haproxy.cfg

services:
  loadbalancer:
    image: haproxytech/haproxy-alpine:latest
    environment:
      - REDIS_SWARM_SECRET=${REDIS_MASTER_AUTH:-redis-swarm}
    networks:
      - rediswarm
    ports:
      - "8404:8404"
      - "6379:6379"
      - "6380:6380"
    configs:
      - source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg

  sentinel:
    <<: *x-redis
    hostname: sentinel-{{.Task.Slot}}
    environment:
      - REDISWARM_MODE=sentinel
      - REDISWARM_SLOT={{.Task.Slot}}
      - REDISWARM_SECRET=${REDIS_MASTER_AUTH:-rediswarm}
      - REDIS_HOSTNAME_PREFIX=${REDIS_HOSTNAME_PREFIX:-redis-}
      - SENTINEL_HOSTNAME_PREFIX=${REDIS_HOSTNAME_PREFIX:-sentinel-}
    networks:
      - rediswarm
    volumes:
      - sentinel-config:/etc/redis/config
    deploy: 
      <<: *x-deploy-default
      replicas: 3

  redis:
    <<: *x-redis
    hostname: redis-{{.Task.Slot}}
    environment:
      - REDISWARM_MODE=redis
      - REDISWARM_SLOT={{.Task.Slot}}
      - REDISWARM_SECRET=${REDIS_MASTER_AUTH:-rediswarm}
      - REDIS_HOSTNAME_PREFIX=${REDIS_HOSTNAME_PREFIX:-redis-}
    networks:
      - rediswarm
    secrets:
      - REDIS_SWARM_SECRET
    configs:
      - source: redis.conf.template
        target: /etc/redis/templates/redis.conf.template
      - source: sentinel.conf.template
        target: /etc/redis/templates/sentinel.conf.template
    volumes:
      - redis:/data
      - redis-config:/etc/redis/config
    deploy: 
      <<: *x-deploy-default
      replicas: 5
