networks:
  rediswarm:

volumes:
  redisinsight:

services:
  redisinsight:
    image: redislabs/redisinsight:latest
    environment:
      - RILOGLEVEL=INFO
    networks:
      - rediswarm
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
